# This is a basic workflow to help you get started with Actions

name: Release Bitstreams

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bitstream:
            - 'bitstream/**'
      - name: get_bitstream_version
        run: chmod +x .github/get_bitstream_version.sh && .github/get_bitstream_version.sh bitstream/default_720p.bit
        shell: bash
      - name: get_spiffs_script
        run: curl https://raw.githubusercontent.com/espressif/esp-idf/master/components/spiffs/spiffsgen.py -o ./spiffsgen.py
        shell: bash
      - name: package_spiffs_image
        run: for file in bitstream/*; do mkdir $(basename $file); cp $file $(basename $file)/bitstream.bit; python spiffsgen.py 0xF0000 $(basename $file)/ $(basename $file)_blueretro.bin; done
        shell: bash
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          # Release title (for automatic releases)
          title: ${{ env.BITSTREAM_VERSION }}
          prerelease: false
          # Assets to upload to the release
          files: |
            bitstream/*.bit
            *.bin
